name: Build VSIX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Compile extension/client only
        run: tsc -p extension/client/tsconfig.json

      - name: Package VSIX
        run: npx vsce package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpgle-extension
          path: '*.vsix'
